#!/usr/bin/env bash
#
# RPIjelly kiosk setup — turns the Pi's desktop into a "media appliance":
#
#   * Boots straight to the desktop and auto-logs-in (no password prompt).
#   * Auto-launches Chromium FULLSCREEN on Jellyfin (http://localhost:8096).
#     We use --start-fullscreen (NOT --kiosk) on purpose, so Alt+Tab still works.
#   * Installs Firefox with uBlock Origin force-installed — use it for YouTube /
#     Google. (Firefox, because Chrome's Manifest V3 crippled uBlock Origin.)
#
# Switch apps with Alt+Tab. uBlock Origin in Firefox handles in-page pop-ups and
# YouTube video ads.
#
# Target: Raspberry Pi OS (Bookworm) on a Pi 5 — labwc/Wayland by default.
# Run after the Docker stack is up, then reboot.

set -euo pipefail

c_grn=$'\e[32m'; c_yel=$'\e[33m'; c_red=$'\e[31m'; c_rst=$'\e[0m'
info()  { printf '%s==>%s %s\n' "$c_grn" "$c_rst" "$*"; }
warn()  { printf '%s[!]%s %s\n' "$c_yel" "$c_rst" "$*"; }
error() { printf '%s[x]%s %s\n' "$c_red" "$c_rst" "$*" >&2; }

if [[ ${EUID} -eq 0 ]]; then
  error "Run as your normal desktop user (not root). It uses sudo where needed."
  exit 1
fi

JELLYFIN_URL="${JELLYFIN_URL:-http://localhost:8096}"
USER_HOME="${HOME}"

# =============================================================================
# 1. Packages: browsers + a few kiosk niceties
# =============================================================================
info "Installing Chromium, Firefox and helpers…"
sudo apt-get update -y
# unclutter hides the mouse cursor when idle; both browsers shipped by Pi OS.
sudo apt-get install -y chromium-browser firefox-esr unclutter || \
  sudo apt-get install -y chromium firefox unclutter

# Resolve the actual chromium binary name (varies by image).
CHROMIUM_BIN="$(command -v chromium-browser || command -v chromium || true)"
if [[ -z "${CHROMIUM_BIN}" ]]; then
  error "Could not find a chromium binary after install."
  exit 1
fi

# =============================================================================
# 2. Boot to desktop with autologin
# =============================================================================
if command -v raspi-config >/dev/null 2>&1; then
  info "Enabling boot-to-desktop with autologin…"
  # B4 = Desktop GUI, automatically logged in as the current user.
  sudo raspi-config nonint do_boot_behaviour B4
else
  warn "raspi-config not found — enable 'Desktop / autologin' yourself (Boot Options)."
fi

# =============================================================================
# 3. Kiosk launch script — waits for Jellyfin, then opens Chromium fullscreen
# =============================================================================
info "Writing the kiosk launcher…"
mkdir -p "${USER_HOME}/.local/bin"
KIOSK_LAUNCHER="${USER_HOME}/.local/bin/rpijelly-kiosk.sh"
cat > "${KIOSK_LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup-kiosk.sh — launches the Jellyfin kiosk.
set -u

JELLYFIN_URL="${JELLYFIN_URL}"
CHROMIUM_BIN="${CHROMIUM_BIN}"

# Hide the cursor when idle.
unclutter -idle 3 &

# Wait until Jellyfin answers before opening the browser (max ~120s).
for i in \$(seq 1 60); do
  if curl -fsS "\${JELLYFIN_URL}/health" >/dev/null 2>&1; then break; fi
  sleep 2
done

# Clear Chromium's "didn't shut down cleanly" nag so it never blocks the kiosk.
PROFILE="\${HOME}/.config/chromium/Default/Preferences"
if [[ -f "\${PROFILE}" ]]; then
  sed -i 's/"exit_type":"[^"]*"/"exit_type":"Normal"/; s/"exited_cleanly":false/"exited_cleanly":true/' "\${PROFILE}" || true
fi

# --start-fullscreen (NOT --kiosk) so Alt+Tab to Firefox keeps working.
exec "\${CHROMIUM_BIN}" \\
  --start-fullscreen \\
  --app="\${JELLYFIN_URL}/web/" \\
  --noerrdialogs \\
  --disable-infobars \\
  --disable-session-crashed-bubble \\
  --check-for-update-interval=31536000 \\
  --no-first-run \\
  --ozone-platform-hint=auto
EOF
chmod +x "${KIOSK_LAUNCHER}"

# =============================================================================
# 4. Autostart wiring (covers labwc, wayfire, and XDG desktops)
# =============================================================================
info "Wiring autostart…"

# (a) labwc — the default Wayland compositor on Pi 5 Bookworm.
mkdir -p "${USER_HOME}/.config/labwc"
LABWC_AUTOSTART="${USER_HOME}/.config/labwc/autostart"
touch "${LABWC_AUTOSTART}"
if ! grep -q "rpijelly-kiosk.sh" "${LABWC_AUTOSTART}" 2>/dev/null; then
  echo "${KIOSK_LAUNCHER} &" >> "${LABWC_AUTOSTART}"
fi

# (b) wayfire — used on some Pi OS images.
if [[ -f "${USER_HOME}/.config/wayfire.ini" ]] || command -v wayfire >/dev/null 2>&1; then
  WAYFIRE_INI="${USER_HOME}/.config/wayfire.ini"
  touch "${WAYFIRE_INI}"
  if ! grep -q "rpijelly-kiosk" "${WAYFIRE_INI}" 2>/dev/null; then
    if ! grep -q '^\[autostart\]' "${WAYFIRE_INI}" 2>/dev/null; then
      printf '\n[autostart]\n' >> "${WAYFIRE_INI}"
    fi
    sed -i "/^\[autostart\]/a rpijelly = ${KIOSK_LAUNCHER}" "${WAYFIRE_INI}"
  fi
fi

# (c) XDG autostart — fallback for X11/LXDE and other desktops.
mkdir -p "${USER_HOME}/.config/autostart"
cat > "${USER_HOME}/.config/autostart/rpijelly-kiosk.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=RPIjelly Kiosk
Exec=${KIOSK_LAUNCHER}
X-GNOME-Autostart-enabled=true
EOF

# =============================================================================
# 5. Firefox + uBlock Origin (force-installed via enterprise policy)
# =============================================================================
info "Force-installing uBlock Origin into Firefox…"
# Works for both firefox and firefox-esr; distribution/policies.json is read by
# all Firefox builds. uBlock blocks in-page pop-ups and YouTube video ads.
for ffdir in /usr/lib/firefox-esr/distribution /usr/lib/firefox/distribution \
             /usr/lib/firefox-esr /usr/lib/firefox; do
  if [[ -d "$(dirname "${ffdir}")" ]]; then
    sudo mkdir -p "${ffdir}"
    sudo tee "${ffdir}/policies.json" >/dev/null <<'EOF'
{
  "policies": {
    "ExtensionSettings": {
      "uBlock0@raymondhill.net": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
      }
    },
    "DisableAppUpdate": true
  }
}
EOF
    break
  fi
done

echo
info "Kiosk configured. Reboot to start the appliance:"
warn "    sudo reboot"
echo
cat <<EOF
After reboot:
  - The Pi logs in automatically and opens Chromium fullscreen on Jellyfin.
  - Press Alt+Tab to switch to Firefox (YouTube/Google, with uBlock Origin).
  - To leave fullscreen in Chromium use F11.
EOF
